// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use std::io::{self, Write};
use tracing_subscriber;

use host::game::{run_game_master_interactive, GameCoordinator};
use host::board_init::prompt_place_ships;
use host::network::NetworkConnection;

fn main() {
    // Initialize tracing. To see logs run with RUST_LOG=info (or debug).
    // Initialize tracing. By default we silence very-verbose risc0 debug
    // messages while still allowing users to override via RUST_LOG. We build
    // a base directive that keeps risc0 crates at INFO and then prepend it to
    // any user-provided RUST_LOG so the user's settings take precedence.
    // By default we cap global logging to INFO to avoid noisy risc0 debug
    // output during normal play. To opt into risc0 debug logs set
    // ALLOW_RISC0_DEBUG=1 in your environment (or edit this file).
    if std::env::var("ALLOW_RISC0_DEBUG").is_ok() {
        // Honor RUST_LOG if the user explicitly allows risc0 debug output.
        // This lets advanced users control logging (including risc0 crates).
        let env_filter = tracing_subscriber::filter::EnvFilter::try_from_default_env()
            .unwrap_or_else(|_| tracing_subscriber::filter::EnvFilter::new("info"));
        tracing_subscriber::fmt().with_env_filter(env_filter).init();
    } else {
        // By default, keep overall logging at INFO but completely silence
        // risc0-related crates (set to OFF) even if the user has RUST_LOG set.
        // This ensures the noisy internal verification logs are hidden from
        // players unless they explicitly opt in via ALLOW_RISC0_DEBUG.
        let user_rust_log = std::env::var("RUST_LOG").unwrap_or_else(|_| "info".to_string());
        // Append our risc0 overrides last so they win over any user-provided
        // directives for those crates. OFF completely disables logging.
        let risc0_overrides = "risc0_zkvm=off,risc0_zkp=off,risc0_circuit_rv32im=off,risc0_circuit=off";
        let directives = format!("{},{}", user_rust_log, risc0_overrides);
        let env_filter = tracing_subscriber::filter::EnvFilter::new(directives);
        // Also set the `log` crate max level to INFO so libraries emitting
        // via the `log` facade don't bypass our filter.
        log::set_max_level(log::LevelFilter::Info);
        tracing_subscriber::fmt().with_env_filter(env_filter).init();
    }

    println!("=== ZK Battleship Host ===");

    loop {
        println!("Select an option:\n 1) Local 2-player (no network)\n 2) Host a networked game\n 3) Join a networked game\n 4) Exit");
        print!("> "); io::stdout().flush().ok();
        let mut choice = String::new();
        if io::stdin().read_line(&mut choice).is_err() {
            println!("failed to read input");
            continue;
        }
        match choice.trim() {
            "1" => {
                run_game_master_interactive();
            }
            "2" => {
                // Host a networked game
                print!("Port to listen on (default 7878): "); io::stdout().flush().ok();
                let mut port_s = String::new(); io::stdin().read_line(&mut port_s).ok();
                let port: u16 = port_s.trim().parse().unwrap_or(7878);

                print!("Player name: "); io::stdout().flush().ok();
                let mut name = String::new(); io::stdin().read_line(&mut name).ok();
                let name = name.trim().to_string();

                println!("{}: place your ships", name);
                let state = prompt_place_ships(&name);
                let commit = state.commit();

                match NetworkConnection::host(port) {
                    Ok(net) => {
                        let mut coord = GameCoordinator::new(state, commit, net, name.clone(), true);
                        if let Err(e) = coord.handshake() {
                            eprintln!("Handshake failed: {}", e);
                            continue;
                        }
                        if let Err(e) = coord.play_game() {
                            eprintln!("Game ended with error: {}", e);
                        }
                    }
                    Err(e) => eprintln!("Failed to start host: {}", e),
                }
            }
            "3" => {
                // Join a networked game
                print!("Host IP (default 127.0.0.1): "); io::stdout().flush().ok();
                let mut host = String::new(); io::stdin().read_line(&mut host).ok();
                let host = if host.trim().is_empty() { "127.0.0.1".to_string() } else { host.trim().to_string() };

                print!("Port (default 7878): "); io::stdout().flush().ok();
                let mut port_s = String::new(); io::stdin().read_line(&mut port_s).ok();
                let port: u16 = port_s.trim().parse().unwrap_or(7878);

                print!("Player name: "); io::stdout().flush().ok();
                let mut name = String::new(); io::stdin().read_line(&mut name).ok();
                let name = name.trim().to_string();

                println!("{}: place your ships", name);
                let state = prompt_place_ships(&name);
                let commit = state.commit();

                match NetworkConnection::connect(&host, port) {
                    Ok(net) => {
                        let mut coord = GameCoordinator::new(state, commit, net, name.clone(), false);
                        if let Err(e) = coord.handshake() {
                            eprintln!("Handshake failed: {}", e);
                            continue;
                        }
                        if let Err(e) = coord.play_game() {
                            eprintln!("Game ended with error: {}", e);
                        }
                    }
                    Err(e) => eprintln!("Failed to connect: {}", e),
                }
            }
            "4" => {
                println!("Goodbye");
                break;
            }
            other => {
                println!("Unknown option: {}", other);
            }
        }
    }
}
